"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from kenar import ClientConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o=vn84vm%*%o@v8%jq2@uxc&8*mt&rrpjc51x9%rj3y_4#3e2+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'services',
    'Message',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

KENAR_CLIENT_CONFIG = ClientConfig(
    app_slug = ('eb20cb2e-3650-11f0-8be3-12d73c7dbe6b'),
    api_key = ('eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGVfa2V5XzIiLCJ0eXAiOiJKV1QifQ.eyJhcHBfc2x1ZyI6InNoYXJwLXBvbGxlbi10b25ndWUiLCJhdWQiOiJzZXJ2aWNlcHJvdmlkZXJzIiwiZXhwIjoxNzUyODc2MjE1LCJqdGkiOiIxYzg1NTZiMC0zNGZkLTExZjAtOGJlMy0xMmQ3M2M3ZGJlNmIiLCJpYXQiOjE3NDc2OTIyMTUsImlzcyI6ImRpdmFyIiwic3ViIjoiYXBpa2V5In0.h3Rv6gRzjMl3blGgHOdk-K5Zds9-DcrMjIu8992EhaZaU_jmR2anWQL__Sh8aEbhQoNv_wrZcNmyhtYa_4k4vkqGZiOyr_stvwDD2V53UQ1qjexGIHhkZOIN8tAK0RReT7veqVaUmLSjG9NX-ziXyZWUMon3ZXjDohnr7GHZL3arLmoXbuy-PKrXvNtw-TAgS__ZB9Qq3t8SkdqqKVC0s9Uv-Fp-y0OW0QwRbOPGbtAgY01il0MxSSx1att0T3wscF71JuIZEVNqdxDG53AHLNRYjvWxsvZ9Uwpgv1LUel2NdvBHCmEfAwXdtc2z6hocTIzeg4GX4f26VeZMLCeSSg'),
    oauth_secret =('163291bb061304b667f2482c4e7beee78a9a92e76ff8eaaf9767ef5daecbf876426067f1b691f2a7d39884e1887442a393b3de321b2ab888b77dbd9b58733ede'),
    oauth_redirect_url= 'https://18e4-82-115-24-48.ngrok-free.app/oauth/callback/'

)